stages:
  - install
  - test
  - deploy

cache:
  key: node_modules
  paths:
    - node_modules/

install:
    stage: install
    script:
        - yarn install
    only:
        changes:
        - yarn.lock

test:
    stage: test
    only:
        - master
    script:
        - yarn test


deploy:
    stage: deploy
    only:
        - master
    script:
        - yarn version --patch
        - git push --follow-tags git@gitlab.mycyclone.com:$CI_PROJECT_PATH.git HEAD:$CI_COMMIT_REF_NAME
        - yarn install
        - npm publish

