
stages:
  - install
  - test
  - deploy

cache:
  key: node_modules
  paths:
    - node_modules/

install:
    stage: install
    script:
        - yarn install
    only:
        changes:
        - yarn.lock

test:
    stage: test
    only:
        - api
        - pipelines
        - schedules
        - web
        - triggers
        - merge_requests
    before_script:
        - yarn install
    script:
        - yarn test
    tags:
        - tester

deploy:
    stage: deploy
    only:
        - master
    except:
        - pipelines
        - schedules
    before_script:
        - yarn install
    script:
        - yarn version --patch
        - git push --follow-tags git@gitlab.mycyclone.com:$CI_PROJECT_PATH.git HEAD:$CI_COMMIT_REF_NAME
        - yarn install
    tags:
        - builder

