name: Node CI

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node-version: [14.x, 16.x, 18.x]
                os: [macos-latest, windows-latest]
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Use Node.js ${{ matrix.node_version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: "https://registry.npmjs.org/"

            - name: cache
              id: cache
              uses: actions/cache@v2
              with:
                  path: |
                      node_modules
                      */*/node_modules
                  key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

            - name: install
              if: steps.cache.outputs.cache-hit != 'true'
              run: yarn install

            - name: build
              run: yarn build

            - name: test
              run: yarn test --forceExit

            # - name: config git user
            #   run: |
            #     git config --local user.email "yuyicman@gmail.com"
            #     git config --local user.name "Yichong Yu"

            # - name: patch version
            #   run: yarn version --patch

            # - name: Push to master
            #   run: git push --follow-tags origin master

            # - name: Publish to NPM
            #   run: npm publish --access public
            #   env:
            #       NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
